name: mocadev
channels:
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'bioconda'
- !!python/unicode
  'r'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'bcftools=1.3.1=1'
- !!python/unicode
  'bedtools=2.26.0=0'
- !!python/unicode
  'biopython=1.68=py27_0'
- !!python/unicode
  'click=6.6=py27_0'
- !!python/unicode
  'curl=7.45.0=2'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'functools32=3.2.3.2=py27_0'
- !!python/unicode
  'gettext=0.19.8=0'
- !!python/unicode
  'htslib=1.3.2=0'
- !!python/unicode
  'jpeg=9b=0'
- !!python/unicode
  'libxml2=2.9.3=0'
- !!python/unicode
  'mmtf-python=1.0.5=py27_0'
- !!python/unicode
  'perl-digest-hmac=1.03=0'
- !!python/unicode
  'perl-encode-locale=1.05=3'
- !!python/unicode
  'perl-file-listing=6.04=0'
- !!python/unicode
  'perl-html-parser=3.72=0'
- !!python/unicode
  'perl-html-tagset=3.20=0'
- !!python/unicode
  'perl-http-cookies=6.01=0'
- !!python/unicode
  'perl-http-daemon=6.01=0'
- !!python/unicode
  'perl-http-date=6.02=0'
- !!python/unicode
  'perl-http-message=6.11=0'
- !!python/unicode
  'perl-http-negotiate=6.01=0'
- !!python/unicode
  'perl-io-html=1.001=0'
- !!python/unicode
  'perl-io-socket-ssl=2.024=0'
- !!python/unicode
  'perl-libwww-perl=6.15=0'
- !!python/unicode
  'perl-lwp-mediatypes=6.02=0'
- !!python/unicode
  'perl-net-http=6.09=0'
- !!python/unicode
  'perl-net-ssleay=1.74=0'
- !!python/unicode
  'perl-ntlm=1.09=1'
- !!python/unicode
  'perl-threaded=5.22.0=10'
- !!python/unicode
  'perl-uri=1.71=0'
- !!python/unicode
  'perl-www-robotrules=6.02=0'
- !!python/unicode
  'perl-xml-parser=2.44=4'
- !!python/unicode
  'pybedtools=0.7.8=py27_1'
- !!python/unicode
  'pybigwig=0.2.8=py27_0'
- !!python/unicode
  'pysam=0.9.1.4=py27_1'
- !!python/unicode
  'pytest-cov=2.4.0=py27_0'
- !!python/unicode
  'pytest-mpl=0.5=py27_0'
- !!python/unicode
  'python-dateutil=2.3=py27_0'
- !!python/unicode
  'samtools=1.3.1=5'
- !!python/unicode
  'tqdm=4.7.2=py27_0'
- !!python/unicode
  'blas=1.1=openblas'
- !!python/unicode
  'ca-certificates=2016.8.31=0'
- !!python/unicode
  'py=1.4.31=py27_0'
- !!python/unicode
  'python=2.7.12=1'
- !!python/unicode
  'cairo=1.14.8=0'
- !!python/unicode
  'certifi=2016.2.28=py27_0'
- !!python/unicode
  'cffi=1.9.1=py27_0'
- !!python/unicode
  'coverage=4.2=py27_0'
- !!python/unicode
  'cryptography=1.7.1=py27_0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'fontconfig=2.12.1=1'
- !!python/unicode
  'freetype=2.5.5=2'
- !!python/unicode
  'future=0.16.0=py27_1'
- !!python/unicode
  'glib=2.50.2=1'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'harfbuzz=0.9.39=2'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'idna=2.2=py27_0'
- !!python/unicode
  'ipaddress=1.0.18=py27_0'
- !!python/unicode
  'jbig=2.1=0'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libtiff=4.0.6=3'
- !!python/unicode
  'libuuid=1.0.3=0'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'matplotlib=1.5.3=np111py27_1'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'msgpack-python=0.4.8=py27_0'
- !!python/unicode
  'ncurses=5.9=10'
- !!python/unicode
  'numpy=1.11.3=py27_0'
- !!python/unicode
  'openblas=0.2.19=0'
- !!python/unicode
  'openssl=1.0.2j=0'
- !!python/unicode
  'pandas=0.19.2=np111py27_1'
- !!python/unicode
  'pango=1.40.3=1'
- !!python/unicode
  'patsy=0.4.1=py27_0'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pillow=4.0.0=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pixman=0.34.0=0'
- !!python/unicode
  'pyasn1=0.1.9=py27_0'
- !!python/unicode
  'pycairo=1.10.0=py27_0'
- !!python/unicode
  'pycparser=2.17=py27_0'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_2'
- !!python/unicode
  'pytest=3.0.5=py27_0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'pyyaml=3.12=py27_0'
- !!python/unicode
  'qt=5.6.2=3'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'reportlab=3.3.0=py27_0'
- !!python/unicode
  'scipy=0.18.1=np111py27_1'
- !!python/unicode
  'seaborn=0.7.1=py27_0'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'statsmodels=0.6.1=np111py27_1'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'xz=5.2.2=1'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - click-help-colors==0.3
prefix: !!python/unicode '/home/saket/anaconda2/envs/mocadev'

